# Use root/example as user/password credentials
version: '3.3'

services:

  db:
    image: mysql:5.6
    restart: always
    volumes:
      - ./mysql:/etc/mysql/conf.d
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: "dev"
      MYSQL_DATABASE: "party_queue"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
