# Use root/example as user/password credentials
version: '3.3'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: dev

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
